Konrad/x509 field
raphaelrobert/maelstrom pull request #120
Opened 2020-10-15 08:54 UTC by kkohbrok

Fixes #75 and thus partially #21.

2020-10-15 12:51 UTC, franziskuskiefer requested changes
Not sure what this is doing. Please add a description to the PR.

2020-10-16 12:05 UTC, franziskuskiefer reviewed
So the structure of credentials must change. I added some suggestions to this. Because this code basically works we can leave it as is and I'll rewrite it in #74, or you can try to make credentials rusty.

I started on #74, which will touch some of these things as well and there's some stuff missing/that needs changing. I'll hold off on that until this one gets done.

2020-10-16 12:05 UTC, franziskuskiefer commented on src/creds.rs
> +            // TODO: implement getter for identity for X509 certificates
A TODO should always get an issue referenced if possible. We should have an issue that is for implementing x509 support.

2020-10-16 12:05 UTC, franziskuskiefer commented on src/creds.rs
> +            // TODO: implement encoding for X509 certificates
Same here.

2020-10-16 12:10 UTC, kkohbrok commented on src/creds.rs
> +/// Enum for Credential Types. We only need this for encoding/decoding.
Yes, but there is no need for our nice rust structs to look like ugly C structs. So I thought in the `Credentials` struct, we can use an enum that contains the actual data as opposed to a `u16` enum plus something that contains whatever data is specified in that enum.

2020-10-16 12:11 UTC, kkohbrok commented on src/creds.rs
> +    credential: MLSCredentialType,
It does. Note the difference between `MLSCredentialType` and `CredentialType`. It's similar with the `ContentType` in the `MLSPlaintext`, I think.

2020-10-19 13:12 UTC, franziskuskiefer submitted a review, later dismissed
Lets merge and tackle the rewrite together.

2020-10-19 13:28 UTC, franziskuskiefer approved these changes

2020-10-19 14:51 UTC, merged