Update BasicCredential
raphaelrobert/maelstrom pull request #125
Opened 2020-10-15 14:38 UTC by raphaelrobert

This PR addresses some of the changes of https://github.com/mlswg/mls-protocol/pull/350/files

Since the most important change is reverted in https://github.com/mlswg/mls-protocol/pull/402/files, it is not implemented in this PR.

2020-10-16 11:32 UTC, kkohbrok requested changes
Looks good with one change.

2020-10-16 11:32 UTC, kkohbrok commented on src/creds.rs
>  }
I think the `from` implementation a few lines below should be changed accordingly.

2020-10-16 11:43 UTC, franziskuskiefer commented on src/creds.rs
>      Default = 255,
Drive-by: Why does this default to `255` and why is a "default" needed?

2020-10-17 14:58 UTC, kkohbrok approved these changes

2020-10-17 16:03 UTC, merged