tree reorg
raphaelrobert/maelstrom pull request #29
Opened 2020-09-24 08:45 UTC by franziskuskiefer

In order to allow for a clean separation of the tree logic, ratchet tree, key schedule, and the group that build on all of this the tree needs to be re-organised.

This is the first of a series of PRs to achieve this.

cc #27 #28

2020-09-25 07:41 UTC, franziskuskiefer commented
I'm not sure what's going on with travis. The build there is a little flaky right now.

2020-09-28 10:16 UTC, raphaelrobert requested changes
I should have looked more closely at this before writing #38. I thought your intention was to get rid of the `OwnLeaf` concept altogether which I did in #38.
To me #38 looks more succinct than #29, but I may be overlooking something. Maybe I can port whatever is missing from #29 to #38?
I could e.g. apply #25, #24 and #26 to #38.

2020-09-28 10:29 UTC, franziskuskiefer commented
> I should have looked more closely at this before writing #38. I thought your intention was to get rid of the `OwnLeaf` concept altogether which I did in #38.
> To me #38 looks more succinct than #29, but I may be overlooking something. Maybe I can port whatever is missing from #29 to #38?
> I could e.g. apply #25, #24 and #26 to #38.

#38 is more succinct but also missing a lot of what's in here.
If you are able to add the same tests etc to #38, that's fine with me. But note that you pull more code into the main tree again that would be better to life outside (like in `OwnLeaf` here)

2020-09-28 10:33 UTC, franziskuskiefer commented on src/group/mls_group/new_from_welcome.rs
> +            own_leaf.generate_path_secrets(
I don't think that's what has been happening here before though...

2020-09-28 10:33 UTC, franziskuskiefer commented on src/group/mls_group/create_commit.rs
> +            let (commit_secret, kpb, path_option, path_secrets) = provisional_tree
My editor is 80. But rustfmt doesn't care about that.

2020-10-05 12:37 UTC, franziskuskiefer commented on src/group/mls_group/new_from_welcome.rs
> +            tree.merge_public_keys(&new_public_keys, &common_path);
Private keys are stored in `own_leaf`. Only the public keys are returned because they aren't stored in `OwnLeaf`.

2020-10-07 10:51 UTC, franziskuskiefer commented
closing in favour of #66 . The rebase was too messy.

2020-10-07 10:51 UTC, closed without merging